<h2>Видео</h2>
<?php foreach ($this->paginator as $article) { ?>
	<div class="video_wrapper">
		<div>
			<h2><?php echo $article->name_ru; ?></h2>
			 <p class="press_data"><?php echo date('d.m.Y', $article->date); ?></p>
		</div>
		<div class="video_descript">
			<?php if (!empty($article->thumb)) { ?>
				<div class="img"><img src="<?php echo $article->thumb; ?>" alt=""></div>
				<a href="<?php echo Rastor_Url::get('vgallery', array('uri' => $article->uri)); ?>"><img src="design/image/arrow.png" alt="" class="arrow"/></a>
			<?php } ?>			
			<?php echo $article->smallcontent_ru; ?>
			<div class="stock_button"><a class="more" href="<?php echo Rastor_Url::get('vgallery', array('uri' => $article->uri)); ?>">подробнее</a></div>
		</div>
	</div>
<?php } ?>
<div class="pagenator_video">
	 <?php echo $this->paginator; ?>
</div>
