<!Doctype HTML>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		 <?php echo $this->partial('inc.head.phtml'); ?>
	</head>

	<body>
		<div id="conteiner">
			<div id="header">
				<?php echo $this->partial('inc.header.phtml'); ?>
			</div>
			
			
			<div id="content">
			
					<!--левая часть начало-->
					<div id="left_block">
						<div class="category">
							<h2>Наши программы</h2>
							<?php echo $this->action('show', 'index', 'menu', array('menuId' => 4) ); ?>
						</div>
						<div class="banner">
							<?php echo $this->action('show', 'index', 'banners', array('position' => 0)); ?>
							
						</div>
						<div class="infoleft">							
						</div>
						<div class="rss">
							<p>Рассылка новостей</p>
							<input class="mail" type="text" placeholder="Введите Ваш E-mail" name="rss" />
							<a href="">Отписаться</a>
							<input class="button" type="submit" value="Подписаться" name="submit" />
							<div class="clear">&nbsp;</div> 
						</div>
					</div>
					<!--конец левой части-->
					
					<!--правая часть начало-->
					<div id="content_block">
							<div class="press_about">
								<?php echo $this->layout()->content; ?>
							</div>
					</div>
					<div class="clear">&nbsp;</div>
					<!--правая часть конец-->
            
            
			</div><!--CONTENT-->
		</div><!--CONTEINER-->
        
		<div id="footer">
			<?php echo $this->partial('inc.footer.phtml'); ?>
		</div><!--FOOTER-->
	</body>
</html>