			<div class="top">
				<div class="block">
					<span>Печерск</span><br/>
					«Студия Серебрянских» на Печерске <br/>
					Печерский спуск, 13«А», школа №134.<br/>  
					Телефон администратора студии<br/>
					<span>Ирины Дмитриевой 067 230 25 45</span>
				</div>
				<div class="block">
					<span>Козин </span><br/>
					«Студия Серебрянских» в Козине<br/>
					с.Козин, ул.Партизанская, 1. <br/>
					Телефон администратора студии <br/>
					<span>Максима Марценюка 067 109 93 28</span>
				</div>
				<div class="block">
					<span>Оболонь </span><br/>
					«Студия Серебрянских» на Оболони <br/>
					ул.Маршала Тимошенко 13«Б»<br/>
					Телефон администратора студии <br/>
					<span>Наталии Лучко 067 328 28 88</span>
				</div>
			</div>
			<div class="menu">
				<?php echo $this->action('show', 'index', 'menu',array('menuId' => 1)); ?>
			</div>			
			<div id="copyright">
				<span><a href="http://globalvision.com.ua">Создание сайта </a>&copy; Global Vision</span>
			</div>
	
