<?php if ($this->pageCount > 1) { ?>
   
        <ul>
	<?php if (isset($this->previous)) { ?>
	    <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&laquo;</a></li>
	<?php }else{ ?>
	    <li>&laquo;</li>
	<?php } ?>
	<?php if ($this->pageCount > 1) { ?>
	    <?php foreach ($this->pagesInRange as $page) { ?>
		<?php if ($page != $this->current) { ?>
		    <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page ?></a></li>
		<?php } else { ?>
		    <li  class="active"><span><?php echo $page ?></span></li>
		<?php } ?>
	    <?php } ?>
	<?php } ?>
	<?php if (isset($this->next)) { ?>
	    <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">&raquo;</a></li>
	<?php }else{ ?>
	    <li>&raquo;</li>
	<?php } ?>
    </ul>
    
<?php } ?>
